import Vue from 'vue'
import Router from 'vue-router'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _0f1ecc32 = () => interopDefault(import('~/pages/hospital/index.vue' /* webpackChunkName: "" */))
const _383f4654 = () => interopDefault(import('../pages/hospital/index.vue' /* webpackChunkName: "pages/hospital/index" */))
const _5c4c8ae9 = () => interopDefault(import('../pages/widgets/index.vue' /* webpackChunkName: "pages/widgets/index" */))
const _240e605a = () => interopDefault(import('../pages/account/forgot-password.vue' /* webpackChunkName: "pages/account/forgot-password" */))
const _1c23f804 = () => interopDefault(import('../pages/account/login.vue' /* webpackChunkName: "pages/account/login" */))
const _5f73ac1e = () => interopDefault(import('../pages/account/register.vue' /* webpackChunkName: "pages/account/register" */))
const _ad49a796 = () => interopDefault(import('../pages/apps/calendar/index.vue' /* webpackChunkName: "pages/apps/calendar/index" */))
const _33360c62 = () => interopDefault(import('../pages/apps/chat/index.vue' /* webpackChunkName: "pages/apps/chat/index" */))
const _ba86c14c = () => interopDefault(import('../pages/apps/companies/index.vue' /* webpackChunkName: "pages/apps/companies/index" */))
const _7c4db750 = () => interopDefault(import('../pages/apps/file-manager.vue' /* webpackChunkName: "pages/apps/file-manager" */))
const _f042e334 = () => interopDefault(import('../pages/apps/tickets/index.vue' /* webpackChunkName: "pages/apps/tickets/index" */))
const _1b5c1f22 = () => interopDefault(import('../pages/auth/confirm-mail.vue' /* webpackChunkName: "pages/auth/confirm-mail" */))
const _a1846072 = () => interopDefault(import('../pages/auth/confirm-mail-2.vue' /* webpackChunkName: "pages/auth/confirm-mail-2" */))
const _06857040 = () => interopDefault(import('../pages/auth/lock-screen.vue' /* webpackChunkName: "pages/auth/lock-screen" */))
const _75575165 = () => interopDefault(import('../pages/auth/lock-screen-2.vue' /* webpackChunkName: "pages/auth/lock-screen-2" */))
const _51ff165b = () => interopDefault(import('../pages/auth/login.vue' /* webpackChunkName: "pages/auth/login" */))
const _6e004680 = () => interopDefault(import('../pages/auth/login-2.vue' /* webpackChunkName: "pages/auth/login-2" */))
const _3af4bd88 = () => interopDefault(import('../pages/auth/logout.vue' /* webpackChunkName: "pages/auth/logout" */))
const _4b286cad = () => interopDefault(import('../pages/auth/logout-2.vue' /* webpackChunkName: "pages/auth/logout-2" */))
const _e5873e52 = () => interopDefault(import('../pages/auth/recoverpwd.vue' /* webpackChunkName: "pages/auth/recoverpwd" */))
const _2a14783c = () => interopDefault(import('../pages/auth/recoverpwd-2.vue' /* webpackChunkName: "pages/auth/recoverpwd-2" */))
const _7bc8bebe = () => interopDefault(import('../pages/auth/register.vue' /* webpackChunkName: "pages/auth/register" */))
const _b7ba24f4 = () => interopDefault(import('../pages/auth/register-2.vue' /* webpackChunkName: "pages/auth/register-2" */))
const _58fbf195 = () => interopDefault(import('../pages/auth/signin-signup.vue' /* webpackChunkName: "pages/auth/signin-signup" */))
const _0432d17a = () => interopDefault(import('../pages/auth/signin-signup-2.vue' /* webpackChunkName: "pages/auth/signin-signup-2" */))
const _098ab316 = () => interopDefault(import('../pages/charts/apex/index.vue' /* webpackChunkName: "pages/charts/apex/index" */))
const _3dca7ee4 = () => interopDefault(import('../pages/charts/c3/index.vue' /* webpackChunkName: "pages/charts/c3/index" */))
const _92db2640 = () => interopDefault(import('../pages/charts/chartist/index.vue' /* webpackChunkName: "pages/charts/chartist/index" */))
const _39ef7809 = () => interopDefault(import('../pages/charts/chartjs/index.vue' /* webpackChunkName: "pages/charts/chartjs/index" */))
const _2d8d9227 = () => interopDefault(import('../pages/charts/knob.vue' /* webpackChunkName: "pages/charts/knob" */))
const _47bd9651 = () => interopDefault(import('../pages/contacts/list.vue' /* webpackChunkName: "pages/contacts/list" */))
const _dd78d874 = () => interopDefault(import('../pages/contacts/profile.vue' /* webpackChunkName: "pages/contacts/profile" */))
const _59f6b485 = () => interopDefault(import('../pages/dashboard/analytics/index.vue' /* webpackChunkName: "pages/dashboard/analytics/index" */))
const _0d8567dd = () => interopDefault(import('../pages/dashboard/crm/index.vue' /* webpackChunkName: "pages/dashboard/crm/index" */))
const _e897f6ea = () => interopDefault(import('../pages/dashboard/sales/index.vue' /* webpackChunkName: "pages/dashboard/sales/index" */))
const _010c6eb0 = () => interopDefault(import('../pages/ecommerce/cart.vue' /* webpackChunkName: "pages/ecommerce/cart" */))
const _7053c064 = () => interopDefault(import('../pages/ecommerce/checkout.vue' /* webpackChunkName: "pages/ecommerce/checkout" */))
const _34815c40 = () => interopDefault(import('../pages/ecommerce/customers/index.vue' /* webpackChunkName: "pages/ecommerce/customers/index" */))
const _0526cb60 = () => interopDefault(import('../pages/ecommerce/data-products.js' /* webpackChunkName: "pages/ecommerce/data-products" */))
const _b7714590 = () => interopDefault(import('../pages/ecommerce/order-detail.vue' /* webpackChunkName: "pages/ecommerce/order-detail" */))
const _41eeeab0 = () => interopDefault(import('../pages/ecommerce/orders/index.vue' /* webpackChunkName: "pages/ecommerce/orders/index" */))
const _4a558fbc = () => interopDefault(import('../pages/ecommerce/product-create.vue' /* webpackChunkName: "pages/ecommerce/product-create" */))
const _2dc8eb22 = () => interopDefault(import('../pages/ecommerce/products/index.vue' /* webpackChunkName: "pages/ecommerce/products/index" */))
const _6f4d5037 = () => interopDefault(import('../pages/ecommerce/products-grid.vue' /* webpackChunkName: "pages/ecommerce/products-grid" */))
const _8b4b0f08 = () => interopDefault(import('../pages/ecommerce/sellers.vue' /* webpackChunkName: "pages/ecommerce/sellers" */))
const _0e4b2b60 = () => interopDefault(import('../pages/email/data-inbox.js' /* webpackChunkName: "pages/email/data-inbox" */))
const _5f7a61ec = () => interopDefault(import('../pages/email/inbox.vue' /* webpackChunkName: "pages/email/inbox" */))
const _5c13a611 = () => interopDefault(import('../pages/email/sidepanel.vue' /* webpackChunkName: "pages/email/sidepanel" */))
const _588eef86 = () => interopDefault(import('../pages/email/templates.vue' /* webpackChunkName: "pages/email/templates" */))
const _3fa42a7f = () => interopDefault(import('../pages/email/toolbar.vue' /* webpackChunkName: "pages/email/toolbar" */))
const _03b2a33e = () => interopDefault(import('../pages/extended/rangeslider.vue' /* webpackChunkName: "pages/extended/rangeslider" */))
const _83f337dc = () => interopDefault(import('../pages/extended/scrollspy.vue' /* webpackChunkName: "pages/extended/scrollspy" */))
const _60489dc2 = () => interopDefault(import('../pages/extended/sweet-alert.vue' /* webpackChunkName: "pages/extended/sweet-alert" */))
const _50b8f8e5 = () => interopDefault(import('../pages/extended/tour.vue' /* webpackChunkName: "pages/extended/tour" */))
const _5386d8a5 = () => interopDefault(import('../pages/extras/404.vue' /* webpackChunkName: "pages/extras/404" */))
const _403a6a81 = () => interopDefault(import('../pages/extras/404-alt.vue' /* webpackChunkName: "pages/extras/404-alt" */))
const _ef96943c = () => interopDefault(import('../pages/extras/500.vue' /* webpackChunkName: "pages/extras/500" */))
const _c6a6d098 = () => interopDefault(import('../pages/extras/coming-soon.vue' /* webpackChunkName: "pages/extras/coming-soon" */))
const _19b8d400 = () => interopDefault(import('../pages/extras/faqs.vue' /* webpackChunkName: "pages/extras/faqs" */))
const _53dc44cc = () => interopDefault(import('../pages/extras/invoice.vue' /* webpackChunkName: "pages/extras/invoice" */))
const _1363dd58 = () => interopDefault(import('../pages/extras/lightbox.vue' /* webpackChunkName: "pages/extras/lightbox" */))
const _58021000 = () => interopDefault(import('../pages/extras/maintenance.vue' /* webpackChunkName: "pages/extras/maintenance" */))
const _665245b3 = () => interopDefault(import('../pages/extras/pricing.vue' /* webpackChunkName: "pages/extras/pricing" */))
const _1fbd1ef4 = () => interopDefault(import('../pages/extras/search-results.vue' /* webpackChunkName: "pages/extras/search-results" */))
const _7b074322 = () => interopDefault(import('../pages/extras/sitemap.vue' /* webpackChunkName: "pages/extras/sitemap" */))
const _8e754c08 = () => interopDefault(import('../pages/extras/starter.vue' /* webpackChunkName: "pages/extras/starter" */))
const _7e5e02a4 = () => interopDefault(import('../pages/extras/timeline.vue' /* webpackChunkName: "pages/extras/timeline" */))
const _3606db9b = () => interopDefault(import('../pages/forms/advanced.vue' /* webpackChunkName: "pages/forms/advanced" */))
const _6fadc1f0 = () => interopDefault(import('../pages/forms/elements.vue' /* webpackChunkName: "pages/forms/elements" */))
const _7c9642ba = () => interopDefault(import('../pages/forms/file-uploads.vue' /* webpackChunkName: "pages/forms/file-uploads" */))
const _df6fc436 = () => interopDefault(import('../pages/forms/mask.vue' /* webpackChunkName: "pages/forms/mask" */))
const _49373e48 = () => interopDefault(import('../pages/forms/quill.vue' /* webpackChunkName: "pages/forms/quill" */))
const _8180779c = () => interopDefault(import('../pages/forms/validation.vue' /* webpackChunkName: "pages/forms/validation" */))
const _04cff0a4 = () => interopDefault(import('../pages/forms/wizard.vue' /* webpackChunkName: "pages/forms/wizard" */))
const _7d74701d = () => interopDefault(import('../pages/icons/boxicons.vue' /* webpackChunkName: "pages/icons/boxicons" */))
const _4b5a9730 = () => interopDefault(import('../pages/icons/data-fontawesome.js' /* webpackChunkName: "pages/icons/data-fontawesome" */))
const _797817a3 = () => interopDefault(import('../pages/icons/data-material.js' /* webpackChunkName: "pages/icons/data-material" */))
const _8aaf028a = () => interopDefault(import('../pages/icons/data-remix.js' /* webpackChunkName: "pages/icons/data-remix" */))
const _43a6ce25 = () => interopDefault(import('../pages/icons/feather.vue' /* webpackChunkName: "pages/icons/feather" */))
const _0d74c25a = () => interopDefault(import('../pages/icons/font-awesome.vue' /* webpackChunkName: "pages/icons/font-awesome" */))
const _08c5d0b4 = () => interopDefault(import('../pages/icons/mdi.vue' /* webpackChunkName: "pages/icons/mdi" */))
const _740edc4b = () => interopDefault(import('../pages/icons/remix.vue' /* webpackChunkName: "pages/icons/remix" */))
const _26d6acf6 = () => interopDefault(import('../pages/icons/weather.vue' /* webpackChunkName: "pages/icons/weather" */))
const _28b95268 = () => interopDefault(import('../pages/maps/google.vue' /* webpackChunkName: "pages/maps/google" */))
const _21284986 = () => interopDefault(import('../pages/tables/advanced/index.vue' /* webpackChunkName: "pages/tables/advanced/index" */))
const _46b54cdd = () => interopDefault(import('../pages/tables/basic.vue' /* webpackChunkName: "pages/tables/basic" */))
const _497110d2 = () => interopDefault(import('../pages/task/detail.vue' /* webpackChunkName: "pages/task/detail" */))
const _3fabbd8a = () => interopDefault(import('../pages/task/kanban/index.vue' /* webpackChunkName: "pages/task/kanban/index" */))
const _54cf40df = () => interopDefault(import('../pages/task/list.vue' /* webpackChunkName: "pages/task/list" */))
const _41c78550 = () => interopDefault(import('../pages/ui/avatars.vue' /* webpackChunkName: "pages/ui/avatars" */))
const _5e8f971f = () => interopDefault(import('../pages/ui/buttons.vue' /* webpackChunkName: "pages/ui/buttons" */))
const _6054a781 = () => interopDefault(import('../pages/ui/cards.vue' /* webpackChunkName: "pages/ui/cards" */))
const _6e794732 = () => interopDefault(import('../pages/ui/carousel.vue' /* webpackChunkName: "pages/ui/carousel" */))
const _4ecf6420 = () => interopDefault(import('../pages/ui/dropdowns.vue' /* webpackChunkName: "pages/ui/dropdowns" */))
const _0a7655f4 = () => interopDefault(import('../pages/ui/general.vue' /* webpackChunkName: "pages/ui/general" */))
const _5880bb18 = () => interopDefault(import('../pages/ui/grid.vue' /* webpackChunkName: "pages/ui/grid" */))
const _0896ba6c = () => interopDefault(import('../pages/ui/images.vue' /* webpackChunkName: "pages/ui/images" */))
const _7f6b983c = () => interopDefault(import('../pages/ui/list-group.vue' /* webpackChunkName: "pages/ui/list-group" */))
const _08d95690 = () => interopDefault(import('../pages/ui/modals.vue' /* webpackChunkName: "pages/ui/modals" */))
const _d51cb6f4 = () => interopDefault(import('../pages/ui/notifications.vue' /* webpackChunkName: "pages/ui/notifications" */))
const _6ad0230b = () => interopDefault(import('../pages/ui/portlets.vue' /* webpackChunkName: "pages/ui/portlets" */))
const _32ba797f = () => interopDefault(import('../pages/ui/progress.vue' /* webpackChunkName: "pages/ui/progress" */))
const _7ec47ffb = () => interopDefault(import('../pages/ui/ribbons.vue' /* webpackChunkName: "pages/ui/ribbons" */))
const _5a1a4b68 = () => interopDefault(import('../pages/ui/spinners.vue' /* webpackChunkName: "pages/ui/spinners" */))
const _1513bef8 = () => interopDefault(import('../pages/ui/tabs-accordions.vue' /* webpackChunkName: "pages/ui/tabs-accordions" */))
const _4a2c25e9 = () => interopDefault(import('../pages/ui/tooltips-popovers.vue' /* webpackChunkName: "pages/ui/tooltips-popovers" */))
const _ae9a15fe = () => interopDefault(import('../pages/ui/typography.vue' /* webpackChunkName: "pages/ui/typography" */))
const _8550eece = () => interopDefault(import('../pages/ui/video.vue' /* webpackChunkName: "pages/ui/video" */))
const _b01ba368 = () => interopDefault(import('../pages/widgets/data.js' /* webpackChunkName: "pages/widgets/data" */))
const _ef2d67aa = () => interopDefault(import('../pages/apps/calendar/data-calendar.js' /* webpackChunkName: "pages/apps/calendar/data-calendar" */))
const _a9f5c29c = () => interopDefault(import('../pages/apps/chat/data.js' /* webpackChunkName: "pages/apps/chat/data" */))
const _638eaafd = () => interopDefault(import('../pages/apps/companies/data.js' /* webpackChunkName: "pages/apps/companies/data" */))
const _4a38ed09 = () => interopDefault(import('../pages/apps/tickets/data.js' /* webpackChunkName: "pages/apps/tickets/data" */))
const _49067db9 = () => interopDefault(import('../pages/charts/apex/data.js' /* webpackChunkName: "pages/charts/apex/data" */))
const _0a7a35f2 = () => interopDefault(import('../pages/charts/c3/data.js' /* webpackChunkName: "pages/charts/c3/data" */))
const _0f662203 = () => interopDefault(import('../pages/charts/chartist/data.js' /* webpackChunkName: "pages/charts/chartist/data" */))
const _1357ca78 = () => interopDefault(import('../pages/charts/chartjs/BarChart.vue' /* webpackChunkName: "pages/charts/chartjs/BarChart" */))
const _01da4455 = () => interopDefault(import('../pages/charts/chartjs/DonutChart.vue' /* webpackChunkName: "pages/charts/chartjs/DonutChart" */))
const _67532be1 = () => interopDefault(import('../pages/charts/chartjs/LineChart.vue' /* webpackChunkName: "pages/charts/chartjs/LineChart" */))
const _bd14052a = () => interopDefault(import('../pages/charts/chartjs/PieChart.vue' /* webpackChunkName: "pages/charts/chartjs/PieChart" */))
const _0328d88e = () => interopDefault(import('../pages/charts/chartjs/PolarChart.vue' /* webpackChunkName: "pages/charts/chartjs/PolarChart" */))
const _796fa0f1 = () => interopDefault(import('../pages/charts/chartjs/RadarChart.vue' /* webpackChunkName: "pages/charts/chartjs/RadarChart" */))
const _17c5e26d = () => interopDefault(import('../pages/dashboard/analytics/channels.vue' /* webpackChunkName: "pages/dashboard/analytics/channels" */))
const _7c88a0d4 = () => interopDefault(import('../pages/dashboard/analytics/overview.vue' /* webpackChunkName: "pages/dashboard/analytics/overview" */))
const _6871cfa1 = () => interopDefault(import('../pages/dashboard/analytics/social-media.vue' /* webpackChunkName: "pages/dashboard/analytics/social-media" */))
const _bc07acaa = () => interopDefault(import('../pages/dashboard/analytics/sources.vue' /* webpackChunkName: "pages/dashboard/analytics/sources" */))
const _c13ee28a = () => interopDefault(import('../pages/dashboard/analytics/users.vue' /* webpackChunkName: "pages/dashboard/analytics/users" */))
const _69096963 = () => interopDefault(import('../pages/ecommerce/customers/data.js' /* webpackChunkName: "pages/ecommerce/customers/data" */))
const _5730585a = () => interopDefault(import('../pages/ecommerce/orders/data.js' /* webpackChunkName: "pages/ecommerce/orders/data" */))
const _8531515c = () => interopDefault(import('../pages/ecommerce/products/data.js' /* webpackChunkName: "pages/ecommerce/products/data" */))
const _1af6f029 = () => interopDefault(import('../pages/tables/advanced/data.js' /* webpackChunkName: "pages/tables/advanced/data" */))
const _0485311e = () => interopDefault(import('../pages/task/kanban/data.js' /* webpackChunkName: "pages/task/kanban/data" */))
const _4d2211bc = () => interopDefault(import('../pages/ecommerce/product-detail/_id.vue' /* webpackChunkName: "pages/ecommerce/product-detail/_id" */))
const _695a4ef5 = () => interopDefault(import('../pages/email/reademail/_id.vue' /* webpackChunkName: "pages/email/reademail/_id" */))

// TODO: remove in Nuxt 3
const emptyFn = () => {}
const originalPush = Router.prototype.push
Router.prototype.push = function push (location, onComplete = emptyFn, onAbort) {
  return originalPush.call(this, location, onComplete, onAbort)
}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: decodeURI('/'),
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _0f1ecc32
  }, {
    path: "/es",
    component: _0f1ecc32
  }, {
    path: "/fr",
    component: _0f1ecc32
  }, {
    path: "/hospital",
    component: _383f4654,
    name: "hospital___en"
  }, {
    path: "/widgets",
    component: _5c4c8ae9,
    name: "widgets___en"
  }, {
    path: "/account/forgot-password",
    component: _240e605a,
    name: "account-forgot-password___en"
  }, {
    path: "/account/login",
    component: _1c23f804,
    name: "account-login___en"
  }, {
    path: "/account/register",
    component: _5f73ac1e,
    name: "account-register___en"
  }, {
    path: "/apps/calendar",
    component: _ad49a796,
    name: "apps-calendar___en"
  }, {
    path: "/apps/chat",
    component: _33360c62,
    name: "apps-chat___en"
  }, {
    path: "/apps/companies",
    component: _ba86c14c,
    name: "apps-companies___en"
  }, {
    path: "/apps/file-manager",
    component: _7c4db750,
    name: "apps-file-manager___en"
  }, {
    path: "/apps/tickets",
    component: _f042e334,
    name: "apps-tickets___en"
  }, {
    path: "/ar/hospital",
    component: _383f4654,
    name: "hospital___ar"
  }, {
    path: "/ar/widgets",
    component: _5c4c8ae9,
    name: "widgets___ar"
  }, {
    path: "/auth/confirm-mail",
    component: _1b5c1f22,
    name: "auth-confirm-mail___en"
  }, {
    path: "/auth/confirm-mail-2",
    component: _a1846072,
    name: "auth-confirm-mail-2___en"
  }, {
    path: "/auth/lock-screen",
    component: _06857040,
    name: "auth-lock-screen___en"
  }, {
    path: "/auth/lock-screen-2",
    component: _75575165,
    name: "auth-lock-screen-2___en"
  }, {
    path: "/auth/login",
    component: _51ff165b,
    name: "auth-login___en"
  }, {
    path: "/auth/login-2",
    component: _6e004680,
    name: "auth-login-2___en"
  }, {
    path: "/auth/logout",
    component: _3af4bd88,
    name: "auth-logout___en"
  }, {
    path: "/auth/logout-2",
    component: _4b286cad,
    name: "auth-logout-2___en"
  }, {
    path: "/auth/recoverpwd",
    component: _e5873e52,
    name: "auth-recoverpwd___en"
  }, {
    path: "/auth/recoverpwd-2",
    component: _2a14783c,
    name: "auth-recoverpwd-2___en"
  }, {
    path: "/auth/register",
    component: _7bc8bebe,
    name: "auth-register___en"
  }, {
    path: "/auth/register-2",
    component: _b7ba24f4,
    name: "auth-register-2___en"
  }, {
    path: "/auth/signin-signup",
    component: _58fbf195,
    name: "auth-signin-signup___en"
  }, {
    path: "/auth/signin-signup-2",
    component: _0432d17a,
    name: "auth-signin-signup-2___en"
  }, {
    path: "/charts/apex",
    component: _098ab316,
    name: "charts-apex___en"
  }, {
    path: "/charts/c3",
    component: _3dca7ee4,
    name: "charts-c3___en"
  }, {
    path: "/charts/chartist",
    component: _92db2640,
    name: "charts-chartist___en"
  }, {
    path: "/charts/chartjs",
    component: _39ef7809,
    name: "charts-chartjs___en"
  }, {
    path: "/charts/knob",
    component: _2d8d9227,
    name: "charts-knob___en"
  }, {
    path: "/contacts/list",
    component: _47bd9651,
    name: "contacts-list___en"
  }, {
    path: "/contacts/profile",
    component: _dd78d874,
    name: "contacts-profile___en"
  }, {
    path: "/dashboard/analytics",
    component: _59f6b485,
    name: "dashboard-analytics___en"
  }, {
    path: "/dashboard/crm",
    component: _0d8567dd,
    name: "dashboard-crm___en"
  }, {
    path: "/dashboard/sales",
    component: _e897f6ea,
    name: "dashboard-sales___en"
  }, {
    path: "/ecommerce/cart",
    component: _010c6eb0,
    name: "ecommerce-cart___en"
  }, {
    path: "/ecommerce/checkout",
    component: _7053c064,
    name: "ecommerce-checkout___en"
  }, {
    path: "/ecommerce/customers",
    component: _34815c40,
    name: "ecommerce-customers___en"
  }, {
    path: "/ecommerce/data-products",
    component: _0526cb60,
    name: "ecommerce-data-products___en"
  }, {
    path: "/ecommerce/order-detail",
    component: _b7714590,
    name: "ecommerce-order-detail___en"
  }, {
    path: "/ecommerce/orders",
    component: _41eeeab0,
    name: "ecommerce-orders___en"
  }, {
    path: "/ecommerce/product-create",
    component: _4a558fbc,
    name: "ecommerce-product-create___en"
  }, {
    path: "/ecommerce/products",
    component: _2dc8eb22,
    name: "ecommerce-products___en"
  }, {
    path: "/ecommerce/products-grid",
    component: _6f4d5037,
    name: "ecommerce-products-grid___en"
  }, {
    path: "/ecommerce/sellers",
    component: _8b4b0f08,
    name: "ecommerce-sellers___en"
  }, {
    path: "/email/data-inbox",
    component: _0e4b2b60,
    name: "email-data-inbox___en"
  }, {
    path: "/email/inbox",
    component: _5f7a61ec,
    name: "email-inbox___en"
  }, {
    path: "/email/sidepanel",
    component: _5c13a611,
    name: "email-sidepanel___en"
  }, {
    path: "/email/templates",
    component: _588eef86,
    name: "email-templates___en"
  }, {
    path: "/email/toolbar",
    component: _3fa42a7f,
    name: "email-toolbar___en"
  }, {
    path: "/es/hospital",
    component: _383f4654,
    name: "hospital___es"
  }, {
    path: "/es/widgets",
    component: _5c4c8ae9,
    name: "widgets___es"
  }, {
    path: "/extended/rangeslider",
    component: _03b2a33e,
    name: "extended-rangeslider___en"
  }, {
    path: "/extended/scrollspy",
    component: _83f337dc,
    name: "extended-scrollspy___en"
  }, {
    path: "/extended/sweet-alert",
    component: _60489dc2,
    name: "extended-sweet-alert___en"
  }, {
    path: "/extended/tour",
    component: _50b8f8e5,
    name: "extended-tour___en"
  }, {
    path: "/extras/404",
    component: _5386d8a5,
    name: "extras-404___en"
  }, {
    path: "/extras/404-alt",
    component: _403a6a81,
    name: "extras-404-alt___en"
  }, {
    path: "/extras/500",
    component: _ef96943c,
    name: "extras-500___en"
  }, {
    path: "/extras/coming-soon",
    component: _c6a6d098,
    name: "extras-coming-soon___en"
  }, {
    path: "/extras/faqs",
    component: _19b8d400,
    name: "extras-faqs___en"
  }, {
    path: "/extras/invoice",
    component: _53dc44cc,
    name: "extras-invoice___en"
  }, {
    path: "/extras/lightbox",
    component: _1363dd58,
    name: "extras-lightbox___en"
  }, {
    path: "/extras/maintenance",
    component: _58021000,
    name: "extras-maintenance___en"
  }, {
    path: "/extras/pricing",
    component: _665245b3,
    name: "extras-pricing___en"
  }, {
    path: "/extras/search-results",
    component: _1fbd1ef4,
    name: "extras-search-results___en"
  }, {
    path: "/extras/sitemap",
    component: _7b074322,
    name: "extras-sitemap___en"
  }, {
    path: "/extras/starter",
    component: _8e754c08,
    name: "extras-starter___en"
  }, {
    path: "/extras/timeline",
    component: _7e5e02a4,
    name: "extras-timeline___en"
  }, {
    path: "/forms/advanced",
    component: _3606db9b,
    name: "forms-advanced___en"
  }, {
    path: "/forms/elements",
    component: _6fadc1f0,
    name: "forms-elements___en"
  }, {
    path: "/forms/file-uploads",
    component: _7c9642ba,
    name: "forms-file-uploads___en"
  }, {
    path: "/forms/mask",
    component: _df6fc436,
    name: "forms-mask___en"
  }, {
    path: "/forms/quill",
    component: _49373e48,
    name: "forms-quill___en"
  }, {
    path: "/forms/validation",
    component: _8180779c,
    name: "forms-validation___en"
  }, {
    path: "/forms/wizard",
    component: _04cff0a4,
    name: "forms-wizard___en"
  }, {
    path: "/fr/hospital",
    component: _383f4654,
    name: "hospital___fr"
  }, {
    path: "/fr/widgets",
    component: _5c4c8ae9,
    name: "widgets___fr"
  }, {
    path: "/icons/boxicons",
    component: _7d74701d,
    name: "icons-boxicons___en"
  }, {
    path: "/icons/data-fontawesome",
    component: _4b5a9730,
    name: "icons-data-fontawesome___en"
  }, {
    path: "/icons/data-material",
    component: _797817a3,
    name: "icons-data-material___en"
  }, {
    path: "/icons/data-remix",
    component: _8aaf028a,
    name: "icons-data-remix___en"
  }, {
    path: "/icons/feather",
    component: _43a6ce25,
    name: "icons-feather___en"
  }, {
    path: "/icons/font-awesome",
    component: _0d74c25a,
    name: "icons-font-awesome___en"
  }, {
    path: "/icons/mdi",
    component: _08c5d0b4,
    name: "icons-mdi___en"
  }, {
    path: "/icons/remix",
    component: _740edc4b,
    name: "icons-remix___en"
  }, {
    path: "/icons/weather",
    component: _26d6acf6,
    name: "icons-weather___en"
  }, {
    path: "/maps/google",
    component: _28b95268,
    name: "maps-google___en"
  }, {
    path: "/tables/advanced",
    component: _21284986,
    name: "tables-advanced___en"
  }, {
    path: "/tables/basic",
    component: _46b54cdd,
    name: "tables-basic___en"
  }, {
    path: "/task/detail",
    component: _497110d2,
    name: "task-detail___en"
  }, {
    path: "/task/kanban",
    component: _3fabbd8a,
    name: "task-kanban___en"
  }, {
    path: "/task/list",
    component: _54cf40df,
    name: "task-list___en"
  }, {
    path: "/ui/avatars",
    component: _41c78550,
    name: "ui-avatars___en"
  }, {
    path: "/ui/buttons",
    component: _5e8f971f,
    name: "ui-buttons___en"
  }, {
    path: "/ui/cards",
    component: _6054a781,
    name: "ui-cards___en"
  }, {
    path: "/ui/carousel",
    component: _6e794732,
    name: "ui-carousel___en"
  }, {
    path: "/ui/dropdowns",
    component: _4ecf6420,
    name: "ui-dropdowns___en"
  }, {
    path: "/ui/general",
    component: _0a7655f4,
    name: "ui-general___en"
  }, {
    path: "/ui/grid",
    component: _5880bb18,
    name: "ui-grid___en"
  }, {
    path: "/ui/images",
    component: _0896ba6c,
    name: "ui-images___en"
  }, {
    path: "/ui/list-group",
    component: _7f6b983c,
    name: "ui-list-group___en"
  }, {
    path: "/ui/modals",
    component: _08d95690,
    name: "ui-modals___en"
  }, {
    path: "/ui/notifications",
    component: _d51cb6f4,
    name: "ui-notifications___en"
  }, {
    path: "/ui/portlets",
    component: _6ad0230b,
    name: "ui-portlets___en"
  }, {
    path: "/ui/progress",
    component: _32ba797f,
    name: "ui-progress___en"
  }, {
    path: "/ui/ribbons",
    component: _7ec47ffb,
    name: "ui-ribbons___en"
  }, {
    path: "/ui/spinners",
    component: _5a1a4b68,
    name: "ui-spinners___en"
  }, {
    path: "/ui/tabs-accordions",
    component: _1513bef8,
    name: "ui-tabs-accordions___en"
  }, {
    path: "/ui/tooltips-popovers",
    component: _4a2c25e9,
    name: "ui-tooltips-popovers___en"
  }, {
    path: "/ui/typography",
    component: _ae9a15fe,
    name: "ui-typography___en"
  }, {
    path: "/ui/video",
    component: _8550eece,
    name: "ui-video___en"
  }, {
    path: "/widgets/data",
    component: _b01ba368,
    name: "widgets-data___en"
  }, {
    path: "/apps/calendar/data-calendar",
    component: _ef2d67aa,
    name: "apps-calendar-data-calendar___en"
  }, {
    path: "/apps/chat/data",
    component: _a9f5c29c,
    name: "apps-chat-data___en"
  }, {
    path: "/apps/companies/data",
    component: _638eaafd,
    name: "apps-companies-data___en"
  }, {
    path: "/apps/tickets/data",
    component: _4a38ed09,
    name: "apps-tickets-data___en"
  }, {
    path: "/ar/account/forgot-password",
    component: _240e605a,
    name: "account-forgot-password___ar"
  }, {
    path: "/ar/account/login",
    component: _1c23f804,
    name: "account-login___ar"
  }, {
    path: "/ar/account/register",
    component: _5f73ac1e,
    name: "account-register___ar"
  }, {
    path: "/ar/apps/calendar",
    component: _ad49a796,
    name: "apps-calendar___ar"
  }, {
    path: "/ar/apps/chat",
    component: _33360c62,
    name: "apps-chat___ar"
  }, {
    path: "/ar/apps/companies",
    component: _ba86c14c,
    name: "apps-companies___ar"
  }, {
    path: "/ar/apps/file-manager",
    component: _7c4db750,
    name: "apps-file-manager___ar"
  }, {
    path: "/ar/apps/tickets",
    component: _f042e334,
    name: "apps-tickets___ar"
  }, {
    path: "/ar/auth/confirm-mail",
    component: _1b5c1f22,
    name: "auth-confirm-mail___ar"
  }, {
    path: "/ar/auth/confirm-mail-2",
    component: _a1846072,
    name: "auth-confirm-mail-2___ar"
  }, {
    path: "/ar/auth/lock-screen",
    component: _06857040,
    name: "auth-lock-screen___ar"
  }, {
    path: "/ar/auth/lock-screen-2",
    component: _75575165,
    name: "auth-lock-screen-2___ar"
  }, {
    path: "/ar/auth/login",
    component: _51ff165b,
    name: "auth-login___ar"
  }, {
    path: "/ar/auth/login-2",
    component: _6e004680,
    name: "auth-login-2___ar"
  }, {
    path: "/ar/auth/logout",
    component: _3af4bd88,
    name: "auth-logout___ar"
  }, {
    path: "/ar/auth/logout-2",
    component: _4b286cad,
    name: "auth-logout-2___ar"
  }, {
    path: "/ar/auth/recoverpwd",
    component: _e5873e52,
    name: "auth-recoverpwd___ar"
  }, {
    path: "/ar/auth/recoverpwd-2",
    component: _2a14783c,
    name: "auth-recoverpwd-2___ar"
  }, {
    path: "/ar/auth/register",
    component: _7bc8bebe,
    name: "auth-register___ar"
  }, {
    path: "/ar/auth/register-2",
    component: _b7ba24f4,
    name: "auth-register-2___ar"
  }, {
    path: "/ar/auth/signin-signup",
    component: _58fbf195,
    name: "auth-signin-signup___ar"
  }, {
    path: "/ar/auth/signin-signup-2",
    component: _0432d17a,
    name: "auth-signin-signup-2___ar"
  }, {
    path: "/ar/charts/apex",
    component: _098ab316,
    name: "charts-apex___ar"
  }, {
    path: "/ar/charts/c3",
    component: _3dca7ee4,
    name: "charts-c3___ar"
  }, {
    path: "/ar/charts/chartist",
    component: _92db2640,
    name: "charts-chartist___ar"
  }, {
    path: "/ar/charts/chartjs",
    component: _39ef7809,
    name: "charts-chartjs___ar"
  }, {
    path: "/ar/charts/knob",
    component: _2d8d9227,
    name: "charts-knob___ar"
  }, {
    path: "/ar/contacts/list",
    component: _47bd9651,
    name: "contacts-list___ar"
  }, {
    path: "/ar/contacts/profile",
    component: _dd78d874,
    name: "contacts-profile___ar"
  }, {
    path: "/ar/dashboard/analytics",
    component: _59f6b485,
    name: "dashboard-analytics___ar"
  }, {
    path: "/ar/dashboard/crm",
    component: _0d8567dd,
    name: "dashboard-crm___ar"
  }, {
    path: "/ar/dashboard/sales",
    component: _e897f6ea,
    name: "dashboard-sales___ar"
  }, {
    path: "/ar/ecommerce/cart",
    component: _010c6eb0,
    name: "ecommerce-cart___ar"
  }, {
    path: "/ar/ecommerce/checkout",
    component: _7053c064,
    name: "ecommerce-checkout___ar"
  }, {
    path: "/ar/ecommerce/customers",
    component: _34815c40,
    name: "ecommerce-customers___ar"
  }, {
    path: "/ar/ecommerce/data-products",
    component: _0526cb60,
    name: "ecommerce-data-products___ar"
  }, {
    path: "/ar/ecommerce/order-detail",
    component: _b7714590,
    name: "ecommerce-order-detail___ar"
  }, {
    path: "/ar/ecommerce/orders",
    component: _41eeeab0,
    name: "ecommerce-orders___ar"
  }, {
    path: "/ar/ecommerce/product-create",
    component: _4a558fbc,
    name: "ecommerce-product-create___ar"
  }, {
    path: "/ar/ecommerce/products",
    component: _2dc8eb22,
    name: "ecommerce-products___ar"
  }, {
    path: "/ar/ecommerce/products-grid",
    component: _6f4d5037,
    name: "ecommerce-products-grid___ar"
  }, {
    path: "/ar/ecommerce/sellers",
    component: _8b4b0f08,
    name: "ecommerce-sellers___ar"
  }, {
    path: "/ar/email/data-inbox",
    component: _0e4b2b60,
    name: "email-data-inbox___ar"
  }, {
    path: "/ar/email/inbox",
    component: _5f7a61ec,
    name: "email-inbox___ar"
  }, {
    path: "/ar/email/sidepanel",
    component: _5c13a611,
    name: "email-sidepanel___ar"
  }, {
    path: "/ar/email/templates",
    component: _588eef86,
    name: "email-templates___ar"
  }, {
    path: "/ar/email/toolbar",
    component: _3fa42a7f,
    name: "email-toolbar___ar"
  }, {
    path: "/ar/extended/rangeslider",
    component: _03b2a33e,
    name: "extended-rangeslider___ar"
  }, {
    path: "/ar/extended/scrollspy",
    component: _83f337dc,
    name: "extended-scrollspy___ar"
  }, {
    path: "/ar/extended/sweet-alert",
    component: _60489dc2,
    name: "extended-sweet-alert___ar"
  }, {
    path: "/ar/extended/tour",
    component: _50b8f8e5,
    name: "extended-tour___ar"
  }, {
    path: "/ar/extras/404",
    component: _5386d8a5,
    name: "extras-404___ar"
  }, {
    path: "/ar/extras/404-alt",
    component: _403a6a81,
    name: "extras-404-alt___ar"
  }, {
    path: "/ar/extras/500",
    component: _ef96943c,
    name: "extras-500___ar"
  }, {
    path: "/ar/extras/coming-soon",
    component: _c6a6d098,
    name: "extras-coming-soon___ar"
  }, {
    path: "/ar/extras/faqs",
    component: _19b8d400,
    name: "extras-faqs___ar"
  }, {
    path: "/ar/extras/invoice",
    component: _53dc44cc,
    name: "extras-invoice___ar"
  }, {
    path: "/ar/extras/lightbox",
    component: _1363dd58,
    name: "extras-lightbox___ar"
  }, {
    path: "/ar/extras/maintenance",
    component: _58021000,
    name: "extras-maintenance___ar"
  }, {
    path: "/ar/extras/pricing",
    component: _665245b3,
    name: "extras-pricing___ar"
  }, {
    path: "/ar/extras/search-results",
    component: _1fbd1ef4,
    name: "extras-search-results___ar"
  }, {
    path: "/ar/extras/sitemap",
    component: _7b074322,
    name: "extras-sitemap___ar"
  }, {
    path: "/ar/extras/starter",
    component: _8e754c08,
    name: "extras-starter___ar"
  }, {
    path: "/ar/extras/timeline",
    component: _7e5e02a4,
    name: "extras-timeline___ar"
  }, {
    path: "/ar/forms/advanced",
    component: _3606db9b,
    name: "forms-advanced___ar"
  }, {
    path: "/ar/forms/elements",
    component: _6fadc1f0,
    name: "forms-elements___ar"
  }, {
    path: "/ar/forms/file-uploads",
    component: _7c9642ba,
    name: "forms-file-uploads___ar"
  }, {
    path: "/ar/forms/mask",
    component: _df6fc436,
    name: "forms-mask___ar"
  }, {
    path: "/ar/forms/quill",
    component: _49373e48,
    name: "forms-quill___ar"
  }, {
    path: "/ar/forms/validation",
    component: _8180779c,
    name: "forms-validation___ar"
  }, {
    path: "/ar/forms/wizard",
    component: _04cff0a4,
    name: "forms-wizard___ar"
  }, {
    path: "/ar/icons/boxicons",
    component: _7d74701d,
    name: "icons-boxicons___ar"
  }, {
    path: "/ar/icons/data-fontawesome",
    component: _4b5a9730,
    name: "icons-data-fontawesome___ar"
  }, {
    path: "/ar/icons/data-material",
    component: _797817a3,
    name: "icons-data-material___ar"
  }, {
    path: "/ar/icons/data-remix",
    component: _8aaf028a,
    name: "icons-data-remix___ar"
  }, {
    path: "/ar/icons/feather",
    component: _43a6ce25,
    name: "icons-feather___ar"
  }, {
    path: "/ar/icons/font-awesome",
    component: _0d74c25a,
    name: "icons-font-awesome___ar"
  }, {
    path: "/ar/icons/mdi",
    component: _08c5d0b4,
    name: "icons-mdi___ar"
  }, {
    path: "/ar/icons/remix",
    component: _740edc4b,
    name: "icons-remix___ar"
  }, {
    path: "/ar/icons/weather",
    component: _26d6acf6,
    name: "icons-weather___ar"
  }, {
    path: "/ar/maps/google",
    component: _28b95268,
    name: "maps-google___ar"
  }, {
    path: "/ar/tables/advanced",
    component: _21284986,
    name: "tables-advanced___ar"
  }, {
    path: "/ar/tables/basic",
    component: _46b54cdd,
    name: "tables-basic___ar"
  }, {
    path: "/ar/task/detail",
    component: _497110d2,
    name: "task-detail___ar"
  }, {
    path: "/ar/task/kanban",
    component: _3fabbd8a,
    name: "task-kanban___ar"
  }, {
    path: "/ar/task/list",
    component: _54cf40df,
    name: "task-list___ar"
  }, {
    path: "/ar/ui/avatars",
    component: _41c78550,
    name: "ui-avatars___ar"
  }, {
    path: "/ar/ui/buttons",
    component: _5e8f971f,
    name: "ui-buttons___ar"
  }, {
    path: "/ar/ui/cards",
    component: _6054a781,
    name: "ui-cards___ar"
  }, {
    path: "/ar/ui/carousel",
    component: _6e794732,
    name: "ui-carousel___ar"
  }, {
    path: "/ar/ui/dropdowns",
    component: _4ecf6420,
    name: "ui-dropdowns___ar"
  }, {
    path: "/ar/ui/general",
    component: _0a7655f4,
    name: "ui-general___ar"
  }, {
    path: "/ar/ui/grid",
    component: _5880bb18,
    name: "ui-grid___ar"
  }, {
    path: "/ar/ui/images",
    component: _0896ba6c,
    name: "ui-images___ar"
  }, {
    path: "/ar/ui/list-group",
    component: _7f6b983c,
    name: "ui-list-group___ar"
  }, {
    path: "/ar/ui/modals",
    component: _08d95690,
    name: "ui-modals___ar"
  }, {
    path: "/ar/ui/notifications",
    component: _d51cb6f4,
    name: "ui-notifications___ar"
  }, {
    path: "/ar/ui/portlets",
    component: _6ad0230b,
    name: "ui-portlets___ar"
  }, {
    path: "/ar/ui/progress",
    component: _32ba797f,
    name: "ui-progress___ar"
  }, {
    path: "/ar/ui/ribbons",
    component: _7ec47ffb,
    name: "ui-ribbons___ar"
  }, {
    path: "/ar/ui/spinners",
    component: _5a1a4b68,
    name: "ui-spinners___ar"
  }, {
    path: "/ar/ui/tabs-accordions",
    component: _1513bef8,
    name: "ui-tabs-accordions___ar"
  }, {
    path: "/ar/ui/tooltips-popovers",
    component: _4a2c25e9,
    name: "ui-tooltips-popovers___ar"
  }, {
    path: "/ar/ui/typography",
    component: _ae9a15fe,
    name: "ui-typography___ar"
  }, {
    path: "/ar/ui/video",
    component: _8550eece,
    name: "ui-video___ar"
  }, {
    path: "/ar/widgets/data",
    component: _b01ba368,
    name: "widgets-data___ar"
  }, {
    path: "/charts/apex/data",
    component: _49067db9,
    name: "charts-apex-data___en"
  }, {
    path: "/charts/c3/data",
    component: _0a7a35f2,
    name: "charts-c3-data___en"
  }, {
    path: "/charts/chartist/data",
    component: _0f662203,
    name: "charts-chartist-data___en"
  }, {
    path: "/charts/chartjs/BarChart",
    component: _1357ca78,
    name: "charts-chartjs-BarChart___en"
  }, {
    path: "/charts/chartjs/DonutChart",
    component: _01da4455,
    name: "charts-chartjs-DonutChart___en"
  }, {
    path: "/charts/chartjs/LineChart",
    component: _67532be1,
    name: "charts-chartjs-LineChart___en"
  }, {
    path: "/charts/chartjs/PieChart",
    component: _bd14052a,
    name: "charts-chartjs-PieChart___en"
  }, {
    path: "/charts/chartjs/PolarChart",
    component: _0328d88e,
    name: "charts-chartjs-PolarChart___en"
  }, {
    path: "/charts/chartjs/RadarChart",
    component: _796fa0f1,
    name: "charts-chartjs-RadarChart___en"
  }, {
    path: "/dashboard/analytics/channels",
    component: _17c5e26d,
    name: "dashboard-analytics-channels___en"
  }, {
    path: "/dashboard/analytics/overview",
    component: _7c88a0d4,
    name: "dashboard-analytics-overview___en"
  }, {
    path: "/dashboard/analytics/social-media",
    component: _6871cfa1,
    name: "dashboard-analytics-social-media___en"
  }, {
    path: "/dashboard/analytics/sources",
    component: _bc07acaa,
    name: "dashboard-analytics-sources___en"
  }, {
    path: "/dashboard/analytics/users",
    component: _c13ee28a,
    name: "dashboard-analytics-users___en"
  }, {
    path: "/ecommerce/customers/data",
    component: _69096963,
    name: "ecommerce-customers-data___en"
  }, {
    path: "/ecommerce/orders/data",
    component: _5730585a,
    name: "ecommerce-orders-data___en"
  }, {
    path: "/ecommerce/products/data",
    component: _8531515c,
    name: "ecommerce-products-data___en"
  }, {
    path: "/es/account/forgot-password",
    component: _240e605a,
    name: "account-forgot-password___es"
  }, {
    path: "/es/account/login",
    component: _1c23f804,
    name: "account-login___es"
  }, {
    path: "/es/account/register",
    component: _5f73ac1e,
    name: "account-register___es"
  }, {
    path: "/es/apps/calendar",
    component: _ad49a796,
    name: "apps-calendar___es"
  }, {
    path: "/es/apps/chat",
    component: _33360c62,
    name: "apps-chat___es"
  }, {
    path: "/es/apps/companies",
    component: _ba86c14c,
    name: "apps-companies___es"
  }, {
    path: "/es/apps/file-manager",
    component: _7c4db750,
    name: "apps-file-manager___es"
  }, {
    path: "/es/apps/tickets",
    component: _f042e334,
    name: "apps-tickets___es"
  }, {
    path: "/es/auth/confirm-mail",
    component: _1b5c1f22,
    name: "auth-confirm-mail___es"
  }, {
    path: "/es/auth/confirm-mail-2",
    component: _a1846072,
    name: "auth-confirm-mail-2___es"
  }, {
    path: "/es/auth/lock-screen",
    component: _06857040,
    name: "auth-lock-screen___es"
  }, {
    path: "/es/auth/lock-screen-2",
    component: _75575165,
    name: "auth-lock-screen-2___es"
  }, {
    path: "/es/auth/login",
    component: _51ff165b,
    name: "auth-login___es"
  }, {
    path: "/es/auth/login-2",
    component: _6e004680,
    name: "auth-login-2___es"
  }, {
    path: "/es/auth/logout",
    component: _3af4bd88,
    name: "auth-logout___es"
  }, {
    path: "/es/auth/logout-2",
    component: _4b286cad,
    name: "auth-logout-2___es"
  }, {
    path: "/es/auth/recoverpwd",
    component: _e5873e52,
    name: "auth-recoverpwd___es"
  }, {
    path: "/es/auth/recoverpwd-2",
    component: _2a14783c,
    name: "auth-recoverpwd-2___es"
  }, {
    path: "/es/auth/register",
    component: _7bc8bebe,
    name: "auth-register___es"
  }, {
    path: "/es/auth/register-2",
    component: _b7ba24f4,
    name: "auth-register-2___es"
  }, {
    path: "/es/auth/signin-signup",
    component: _58fbf195,
    name: "auth-signin-signup___es"
  }, {
    path: "/es/auth/signin-signup-2",
    component: _0432d17a,
    name: "auth-signin-signup-2___es"
  }, {
    path: "/es/charts/apex",
    component: _098ab316,
    name: "charts-apex___es"
  }, {
    path: "/es/charts/c3",
    component: _3dca7ee4,
    name: "charts-c3___es"
  }, {
    path: "/es/charts/chartist",
    component: _92db2640,
    name: "charts-chartist___es"
  }, {
    path: "/es/charts/chartjs",
    component: _39ef7809,
    name: "charts-chartjs___es"
  }, {
    path: "/es/charts/knob",
    component: _2d8d9227,
    name: "charts-knob___es"
  }, {
    path: "/es/contacts/list",
    component: _47bd9651,
    name: "contacts-list___es"
  }, {
    path: "/es/contacts/profile",
    component: _dd78d874,
    name: "contacts-profile___es"
  }, {
    path: "/es/dashboard/analytics",
    component: _59f6b485,
    name: "dashboard-analytics___es"
  }, {
    path: "/es/dashboard/crm",
    component: _0d8567dd,
    name: "dashboard-crm___es"
  }, {
    path: "/es/dashboard/sales",
    component: _e897f6ea,
    name: "dashboard-sales___es"
  }, {
    path: "/es/ecommerce/cart",
    component: _010c6eb0,
    name: "ecommerce-cart___es"
  }, {
    path: "/es/ecommerce/checkout",
    component: _7053c064,
    name: "ecommerce-checkout___es"
  }, {
    path: "/es/ecommerce/customers",
    component: _34815c40,
    name: "ecommerce-customers___es"
  }, {
    path: "/es/ecommerce/data-products",
    component: _0526cb60,
    name: "ecommerce-data-products___es"
  }, {
    path: "/es/ecommerce/order-detail",
    component: _b7714590,
    name: "ecommerce-order-detail___es"
  }, {
    path: "/es/ecommerce/orders",
    component: _41eeeab0,
    name: "ecommerce-orders___es"
  }, {
    path: "/es/ecommerce/product-create",
    component: _4a558fbc,
    name: "ecommerce-product-create___es"
  }, {
    path: "/es/ecommerce/products",
    component: _2dc8eb22,
    name: "ecommerce-products___es"
  }, {
    path: "/es/ecommerce/products-grid",
    component: _6f4d5037,
    name: "ecommerce-products-grid___es"
  }, {
    path: "/es/ecommerce/sellers",
    component: _8b4b0f08,
    name: "ecommerce-sellers___es"
  }, {
    path: "/es/email/data-inbox",
    component: _0e4b2b60,
    name: "email-data-inbox___es"
  }, {
    path: "/es/email/inbox",
    component: _5f7a61ec,
    name: "email-inbox___es"
  }, {
    path: "/es/email/sidepanel",
    component: _5c13a611,
    name: "email-sidepanel___es"
  }, {
    path: "/es/email/templates",
    component: _588eef86,
    name: "email-templates___es"
  }, {
    path: "/es/email/toolbar",
    component: _3fa42a7f,
    name: "email-toolbar___es"
  }, {
    path: "/es/extended/rangeslider",
    component: _03b2a33e,
    name: "extended-rangeslider___es"
  }, {
    path: "/es/extended/scrollspy",
    component: _83f337dc,
    name: "extended-scrollspy___es"
  }, {
    path: "/es/extended/sweet-alert",
    component: _60489dc2,
    name: "extended-sweet-alert___es"
  }, {
    path: "/es/extended/tour",
    component: _50b8f8e5,
    name: "extended-tour___es"
  }, {
    path: "/es/extras/404",
    component: _5386d8a5,
    name: "extras-404___es"
  }, {
    path: "/es/extras/404-alt",
    component: _403a6a81,
    name: "extras-404-alt___es"
  }, {
    path: "/es/extras/500",
    component: _ef96943c,
    name: "extras-500___es"
  }, {
    path: "/es/extras/coming-soon",
    component: _c6a6d098,
    name: "extras-coming-soon___es"
  }, {
    path: "/es/extras/faqs",
    component: _19b8d400,
    name: "extras-faqs___es"
  }, {
    path: "/es/extras/invoice",
    component: _53dc44cc,
    name: "extras-invoice___es"
  }, {
    path: "/es/extras/lightbox",
    component: _1363dd58,
    name: "extras-lightbox___es"
  }, {
    path: "/es/extras/maintenance",
    component: _58021000,
    name: "extras-maintenance___es"
  }, {
    path: "/es/extras/pricing",
    component: _665245b3,
    name: "extras-pricing___es"
  }, {
    path: "/es/extras/search-results",
    component: _1fbd1ef4,
    name: "extras-search-results___es"
  }, {
    path: "/es/extras/sitemap",
    component: _7b074322,
    name: "extras-sitemap___es"
  }, {
    path: "/es/extras/starter",
    component: _8e754c08,
    name: "extras-starter___es"
  }, {
    path: "/es/extras/timeline",
    component: _7e5e02a4,
    name: "extras-timeline___es"
  }, {
    path: "/es/forms/advanced",
    component: _3606db9b,
    name: "forms-advanced___es"
  }, {
    path: "/es/forms/elements",
    component: _6fadc1f0,
    name: "forms-elements___es"
  }, {
    path: "/es/forms/file-uploads",
    component: _7c9642ba,
    name: "forms-file-uploads___es"
  }, {
    path: "/es/forms/mask",
    component: _df6fc436,
    name: "forms-mask___es"
  }, {
    path: "/es/forms/quill",
    component: _49373e48,
    name: "forms-quill___es"
  }, {
    path: "/es/forms/validation",
    component: _8180779c,
    name: "forms-validation___es"
  }, {
    path: "/es/forms/wizard",
    component: _04cff0a4,
    name: "forms-wizard___es"
  }, {
    path: "/es/icons/boxicons",
    component: _7d74701d,
    name: "icons-boxicons___es"
  }, {
    path: "/es/icons/data-fontawesome",
    component: _4b5a9730,
    name: "icons-data-fontawesome___es"
  }, {
    path: "/es/icons/data-material",
    component: _797817a3,
    name: "icons-data-material___es"
  }, {
    path: "/es/icons/data-remix",
    component: _8aaf028a,
    name: "icons-data-remix___es"
  }, {
    path: "/es/icons/feather",
    component: _43a6ce25,
    name: "icons-feather___es"
  }, {
    path: "/es/icons/font-awesome",
    component: _0d74c25a,
    name: "icons-font-awesome___es"
  }, {
    path: "/es/icons/mdi",
    component: _08c5d0b4,
    name: "icons-mdi___es"
  }, {
    path: "/es/icons/remix",
    component: _740edc4b,
    name: "icons-remix___es"
  }, {
    path: "/es/icons/weather",
    component: _26d6acf6,
    name: "icons-weather___es"
  }, {
    path: "/es/maps/google",
    component: _28b95268,
    name: "maps-google___es"
  }, {
    path: "/es/tables/advanced",
    component: _21284986,
    name: "tables-advanced___es"
  }, {
    path: "/es/tables/basic",
    component: _46b54cdd,
    name: "tables-basic___es"
  }, {
    path: "/es/task/detail",
    component: _497110d2,
    name: "task-detail___es"
  }, {
    path: "/es/task/kanban",
    component: _3fabbd8a,
    name: "task-kanban___es"
  }, {
    path: "/es/task/list",
    component: _54cf40df,
    name: "task-list___es"
  }, {
    path: "/es/ui/avatars",
    component: _41c78550,
    name: "ui-avatars___es"
  }, {
    path: "/es/ui/buttons",
    component: _5e8f971f,
    name: "ui-buttons___es"
  }, {
    path: "/es/ui/cards",
    component: _6054a781,
    name: "ui-cards___es"
  }, {
    path: "/es/ui/carousel",
    component: _6e794732,
    name: "ui-carousel___es"
  }, {
    path: "/es/ui/dropdowns",
    component: _4ecf6420,
    name: "ui-dropdowns___es"
  }, {
    path: "/es/ui/general",
    component: _0a7655f4,
    name: "ui-general___es"
  }, {
    path: "/es/ui/grid",
    component: _5880bb18,
    name: "ui-grid___es"
  }, {
    path: "/es/ui/images",
    component: _0896ba6c,
    name: "ui-images___es"
  }, {
    path: "/es/ui/list-group",
    component: _7f6b983c,
    name: "ui-list-group___es"
  }, {
    path: "/es/ui/modals",
    component: _08d95690,
    name: "ui-modals___es"
  }, {
    path: "/es/ui/notifications",
    component: _d51cb6f4,
    name: "ui-notifications___es"
  }, {
    path: "/es/ui/portlets",
    component: _6ad0230b,
    name: "ui-portlets___es"
  }, {
    path: "/es/ui/progress",
    component: _32ba797f,
    name: "ui-progress___es"
  }, {
    path: "/es/ui/ribbons",
    component: _7ec47ffb,
    name: "ui-ribbons___es"
  }, {
    path: "/es/ui/spinners",
    component: _5a1a4b68,
    name: "ui-spinners___es"
  }, {
    path: "/es/ui/tabs-accordions",
    component: _1513bef8,
    name: "ui-tabs-accordions___es"
  }, {
    path: "/es/ui/tooltips-popovers",
    component: _4a2c25e9,
    name: "ui-tooltips-popovers___es"
  }, {
    path: "/es/ui/typography",
    component: _ae9a15fe,
    name: "ui-typography___es"
  }, {
    path: "/es/ui/video",
    component: _8550eece,
    name: "ui-video___es"
  }, {
    path: "/es/widgets/data",
    component: _b01ba368,
    name: "widgets-data___es"
  }, {
    path: "/fr/account/forgot-password",
    component: _240e605a,
    name: "account-forgot-password___fr"
  }, {
    path: "/fr/account/login",
    component: _1c23f804,
    name: "account-login___fr"
  }, {
    path: "/fr/account/register",
    component: _5f73ac1e,
    name: "account-register___fr"
  }, {
    path: "/fr/apps/calendar",
    component: _ad49a796,
    name: "apps-calendar___fr"
  }, {
    path: "/fr/apps/chat",
    component: _33360c62,
    name: "apps-chat___fr"
  }, {
    path: "/fr/apps/companies",
    component: _ba86c14c,
    name: "apps-companies___fr"
  }, {
    path: "/fr/apps/file-manager",
    component: _7c4db750,
    name: "apps-file-manager___fr"
  }, {
    path: "/fr/apps/tickets",
    component: _f042e334,
    name: "apps-tickets___fr"
  }, {
    path: "/fr/auth/confirm-mail",
    component: _1b5c1f22,
    name: "auth-confirm-mail___fr"
  }, {
    path: "/fr/auth/confirm-mail-2",
    component: _a1846072,
    name: "auth-confirm-mail-2___fr"
  }, {
    path: "/fr/auth/lock-screen",
    component: _06857040,
    name: "auth-lock-screen___fr"
  }, {
    path: "/fr/auth/lock-screen-2",
    component: _75575165,
    name: "auth-lock-screen-2___fr"
  }, {
    path: "/fr/auth/login",
    component: _51ff165b,
    name: "auth-login___fr"
  }, {
    path: "/fr/auth/login-2",
    component: _6e004680,
    name: "auth-login-2___fr"
  }, {
    path: "/fr/auth/logout",
    component: _3af4bd88,
    name: "auth-logout___fr"
  }, {
    path: "/fr/auth/logout-2",
    component: _4b286cad,
    name: "auth-logout-2___fr"
  }, {
    path: "/fr/auth/recoverpwd",
    component: _e5873e52,
    name: "auth-recoverpwd___fr"
  }, {
    path: "/fr/auth/recoverpwd-2",
    component: _2a14783c,
    name: "auth-recoverpwd-2___fr"
  }, {
    path: "/fr/auth/register",
    component: _7bc8bebe,
    name: "auth-register___fr"
  }, {
    path: "/fr/auth/register-2",
    component: _b7ba24f4,
    name: "auth-register-2___fr"
  }, {
    path: "/fr/auth/signin-signup",
    component: _58fbf195,
    name: "auth-signin-signup___fr"
  }, {
    path: "/fr/auth/signin-signup-2",
    component: _0432d17a,
    name: "auth-signin-signup-2___fr"
  }, {
    path: "/fr/charts/apex",
    component: _098ab316,
    name: "charts-apex___fr"
  }, {
    path: "/fr/charts/c3",
    component: _3dca7ee4,
    name: "charts-c3___fr"
  }, {
    path: "/fr/charts/chartist",
    component: _92db2640,
    name: "charts-chartist___fr"
  }, {
    path: "/fr/charts/chartjs",
    component: _39ef7809,
    name: "charts-chartjs___fr"
  }, {
    path: "/fr/charts/knob",
    component: _2d8d9227,
    name: "charts-knob___fr"
  }, {
    path: "/fr/contacts/list",
    component: _47bd9651,
    name: "contacts-list___fr"
  }, {
    path: "/fr/contacts/profile",
    component: _dd78d874,
    name: "contacts-profile___fr"
  }, {
    path: "/fr/dashboard/analytics",
    component: _59f6b485,
    name: "dashboard-analytics___fr"
  }, {
    path: "/fr/dashboard/crm",
    component: _0d8567dd,
    name: "dashboard-crm___fr"
  }, {
    path: "/fr/dashboard/sales",
    component: _e897f6ea,
    name: "dashboard-sales___fr"
  }, {
    path: "/fr/ecommerce/cart",
    component: _010c6eb0,
    name: "ecommerce-cart___fr"
  }, {
    path: "/fr/ecommerce/checkout",
    component: _7053c064,
    name: "ecommerce-checkout___fr"
  }, {
    path: "/fr/ecommerce/customers",
    component: _34815c40,
    name: "ecommerce-customers___fr"
  }, {
    path: "/fr/ecommerce/data-products",
    component: _0526cb60,
    name: "ecommerce-data-products___fr"
  }, {
    path: "/fr/ecommerce/order-detail",
    component: _b7714590,
    name: "ecommerce-order-detail___fr"
  }, {
    path: "/fr/ecommerce/orders",
    component: _41eeeab0,
    name: "ecommerce-orders___fr"
  }, {
    path: "/fr/ecommerce/product-create",
    component: _4a558fbc,
    name: "ecommerce-product-create___fr"
  }, {
    path: "/fr/ecommerce/products",
    component: _2dc8eb22,
    name: "ecommerce-products___fr"
  }, {
    path: "/fr/ecommerce/products-grid",
    component: _6f4d5037,
    name: "ecommerce-products-grid___fr"
  }, {
    path: "/fr/ecommerce/sellers",
    component: _8b4b0f08,
    name: "ecommerce-sellers___fr"
  }, {
    path: "/fr/email/data-inbox",
    component: _0e4b2b60,
    name: "email-data-inbox___fr"
  }, {
    path: "/fr/email/inbox",
    component: _5f7a61ec,
    name: "email-inbox___fr"
  }, {
    path: "/fr/email/sidepanel",
    component: _5c13a611,
    name: "email-sidepanel___fr"
  }, {
    path: "/fr/email/templates",
    component: _588eef86,
    name: "email-templates___fr"
  }, {
    path: "/fr/email/toolbar",
    component: _3fa42a7f,
    name: "email-toolbar___fr"
  }, {
    path: "/fr/extended/rangeslider",
    component: _03b2a33e,
    name: "extended-rangeslider___fr"
  }, {
    path: "/fr/extended/scrollspy",
    component: _83f337dc,
    name: "extended-scrollspy___fr"
  }, {
    path: "/fr/extended/sweet-alert",
    component: _60489dc2,
    name: "extended-sweet-alert___fr"
  }, {
    path: "/fr/extended/tour",
    component: _50b8f8e5,
    name: "extended-tour___fr"
  }, {
    path: "/fr/extras/404",
    component: _5386d8a5,
    name: "extras-404___fr"
  }, {
    path: "/fr/extras/404-alt",
    component: _403a6a81,
    name: "extras-404-alt___fr"
  }, {
    path: "/fr/extras/500",
    component: _ef96943c,
    name: "extras-500___fr"
  }, {
    path: "/fr/extras/coming-soon",
    component: _c6a6d098,
    name: "extras-coming-soon___fr"
  }, {
    path: "/fr/extras/faqs",
    component: _19b8d400,
    name: "extras-faqs___fr"
  }, {
    path: "/fr/extras/invoice",
    component: _53dc44cc,
    name: "extras-invoice___fr"
  }, {
    path: "/fr/extras/lightbox",
    component: _1363dd58,
    name: "extras-lightbox___fr"
  }, {
    path: "/fr/extras/maintenance",
    component: _58021000,
    name: "extras-maintenance___fr"
  }, {
    path: "/fr/extras/pricing",
    component: _665245b3,
    name: "extras-pricing___fr"
  }, {
    path: "/fr/extras/search-results",
    component: _1fbd1ef4,
    name: "extras-search-results___fr"
  }, {
    path: "/fr/extras/sitemap",
    component: _7b074322,
    name: "extras-sitemap___fr"
  }, {
    path: "/fr/extras/starter",
    component: _8e754c08,
    name: "extras-starter___fr"
  }, {
    path: "/fr/extras/timeline",
    component: _7e5e02a4,
    name: "extras-timeline___fr"
  }, {
    path: "/fr/forms/advanced",
    component: _3606db9b,
    name: "forms-advanced___fr"
  }, {
    path: "/fr/forms/elements",
    component: _6fadc1f0,
    name: "forms-elements___fr"
  }, {
    path: "/fr/forms/file-uploads",
    component: _7c9642ba,
    name: "forms-file-uploads___fr"
  }, {
    path: "/fr/forms/mask",
    component: _df6fc436,
    name: "forms-mask___fr"
  }, {
    path: "/fr/forms/quill",
    component: _49373e48,
    name: "forms-quill___fr"
  }, {
    path: "/fr/forms/validation",
    component: _8180779c,
    name: "forms-validation___fr"
  }, {
    path: "/fr/forms/wizard",
    component: _04cff0a4,
    name: "forms-wizard___fr"
  }, {
    path: "/fr/icons/boxicons",
    component: _7d74701d,
    name: "icons-boxicons___fr"
  }, {
    path: "/fr/icons/data-fontawesome",
    component: _4b5a9730,
    name: "icons-data-fontawesome___fr"
  }, {
    path: "/fr/icons/data-material",
    component: _797817a3,
    name: "icons-data-material___fr"
  }, {
    path: "/fr/icons/data-remix",
    component: _8aaf028a,
    name: "icons-data-remix___fr"
  }, {
    path: "/fr/icons/feather",
    component: _43a6ce25,
    name: "icons-feather___fr"
  }, {
    path: "/fr/icons/font-awesome",
    component: _0d74c25a,
    name: "icons-font-awesome___fr"
  }, {
    path: "/fr/icons/mdi",
    component: _08c5d0b4,
    name: "icons-mdi___fr"
  }, {
    path: "/fr/icons/remix",
    component: _740edc4b,
    name: "icons-remix___fr"
  }, {
    path: "/fr/icons/weather",
    component: _26d6acf6,
    name: "icons-weather___fr"
  }, {
    path: "/fr/maps/google",
    component: _28b95268,
    name: "maps-google___fr"
  }, {
    path: "/fr/tables/advanced",
    component: _21284986,
    name: "tables-advanced___fr"
  }, {
    path: "/fr/tables/basic",
    component: _46b54cdd,
    name: "tables-basic___fr"
  }, {
    path: "/fr/task/detail",
    component: _497110d2,
    name: "task-detail___fr"
  }, {
    path: "/fr/task/kanban",
    component: _3fabbd8a,
    name: "task-kanban___fr"
  }, {
    path: "/fr/task/list",
    component: _54cf40df,
    name: "task-list___fr"
  }, {
    path: "/fr/ui/avatars",
    component: _41c78550,
    name: "ui-avatars___fr"
  }, {
    path: "/fr/ui/buttons",
    component: _5e8f971f,
    name: "ui-buttons___fr"
  }, {
    path: "/fr/ui/cards",
    component: _6054a781,
    name: "ui-cards___fr"
  }, {
    path: "/fr/ui/carousel",
    component: _6e794732,
    name: "ui-carousel___fr"
  }, {
    path: "/fr/ui/dropdowns",
    component: _4ecf6420,
    name: "ui-dropdowns___fr"
  }, {
    path: "/fr/ui/general",
    component: _0a7655f4,
    name: "ui-general___fr"
  }, {
    path: "/fr/ui/grid",
    component: _5880bb18,
    name: "ui-grid___fr"
  }, {
    path: "/fr/ui/images",
    component: _0896ba6c,
    name: "ui-images___fr"
  }, {
    path: "/fr/ui/list-group",
    component: _7f6b983c,
    name: "ui-list-group___fr"
  }, {
    path: "/fr/ui/modals",
    component: _08d95690,
    name: "ui-modals___fr"
  }, {
    path: "/fr/ui/notifications",
    component: _d51cb6f4,
    name: "ui-notifications___fr"
  }, {
    path: "/fr/ui/portlets",
    component: _6ad0230b,
    name: "ui-portlets___fr"
  }, {
    path: "/fr/ui/progress",
    component: _32ba797f,
    name: "ui-progress___fr"
  }, {
    path: "/fr/ui/ribbons",
    component: _7ec47ffb,
    name: "ui-ribbons___fr"
  }, {
    path: "/fr/ui/spinners",
    component: _5a1a4b68,
    name: "ui-spinners___fr"
  }, {
    path: "/fr/ui/tabs-accordions",
    component: _1513bef8,
    name: "ui-tabs-accordions___fr"
  }, {
    path: "/fr/ui/tooltips-popovers",
    component: _4a2c25e9,
    name: "ui-tooltips-popovers___fr"
  }, {
    path: "/fr/ui/typography",
    component: _ae9a15fe,
    name: "ui-typography___fr"
  }, {
    path: "/fr/ui/video",
    component: _8550eece,
    name: "ui-video___fr"
  }, {
    path: "/fr/widgets/data",
    component: _b01ba368,
    name: "widgets-data___fr"
  }, {
    path: "/tables/advanced/data",
    component: _1af6f029,
    name: "tables-advanced-data___en"
  }, {
    path: "/task/kanban/data",
    component: _0485311e,
    name: "task-kanban-data___en"
  }, {
    path: "/ar/apps/calendar/data-calendar",
    component: _ef2d67aa,
    name: "apps-calendar-data-calendar___ar"
  }, {
    path: "/ar/apps/chat/data",
    component: _a9f5c29c,
    name: "apps-chat-data___ar"
  }, {
    path: "/ar/apps/companies/data",
    component: _638eaafd,
    name: "apps-companies-data___ar"
  }, {
    path: "/ar/apps/tickets/data",
    component: _4a38ed09,
    name: "apps-tickets-data___ar"
  }, {
    path: "/ar/charts/apex/data",
    component: _49067db9,
    name: "charts-apex-data___ar"
  }, {
    path: "/ar/charts/c3/data",
    component: _0a7a35f2,
    name: "charts-c3-data___ar"
  }, {
    path: "/ar/charts/chartist/data",
    component: _0f662203,
    name: "charts-chartist-data___ar"
  }, {
    path: "/ar/charts/chartjs/BarChart",
    component: _1357ca78,
    name: "charts-chartjs-BarChart___ar"
  }, {
    path: "/ar/charts/chartjs/DonutChart",
    component: _01da4455,
    name: "charts-chartjs-DonutChart___ar"
  }, {
    path: "/ar/charts/chartjs/LineChart",
    component: _67532be1,
    name: "charts-chartjs-LineChart___ar"
  }, {
    path: "/ar/charts/chartjs/PieChart",
    component: _bd14052a,
    name: "charts-chartjs-PieChart___ar"
  }, {
    path: "/ar/charts/chartjs/PolarChart",
    component: _0328d88e,
    name: "charts-chartjs-PolarChart___ar"
  }, {
    path: "/ar/charts/chartjs/RadarChart",
    component: _796fa0f1,
    name: "charts-chartjs-RadarChart___ar"
  }, {
    path: "/ar/dashboard/analytics/channels",
    component: _17c5e26d,
    name: "dashboard-analytics-channels___ar"
  }, {
    path: "/ar/dashboard/analytics/overview",
    component: _7c88a0d4,
    name: "dashboard-analytics-overview___ar"
  }, {
    path: "/ar/dashboard/analytics/social-media",
    component: _6871cfa1,
    name: "dashboard-analytics-social-media___ar"
  }, {
    path: "/ar/dashboard/analytics/sources",
    component: _bc07acaa,
    name: "dashboard-analytics-sources___ar"
  }, {
    path: "/ar/dashboard/analytics/users",
    component: _c13ee28a,
    name: "dashboard-analytics-users___ar"
  }, {
    path: "/ar/ecommerce/customers/data",
    component: _69096963,
    name: "ecommerce-customers-data___ar"
  }, {
    path: "/ar/ecommerce/orders/data",
    component: _5730585a,
    name: "ecommerce-orders-data___ar"
  }, {
    path: "/ar/ecommerce/products/data",
    component: _8531515c,
    name: "ecommerce-products-data___ar"
  }, {
    path: "/ar/tables/advanced/data",
    component: _1af6f029,
    name: "tables-advanced-data___ar"
  }, {
    path: "/ar/task/kanban/data",
    component: _0485311e,
    name: "task-kanban-data___ar"
  }, {
    path: "/es/apps/calendar/data-calendar",
    component: _ef2d67aa,
    name: "apps-calendar-data-calendar___es"
  }, {
    path: "/es/apps/chat/data",
    component: _a9f5c29c,
    name: "apps-chat-data___es"
  }, {
    path: "/es/apps/companies/data",
    component: _638eaafd,
    name: "apps-companies-data___es"
  }, {
    path: "/es/apps/tickets/data",
    component: _4a38ed09,
    name: "apps-tickets-data___es"
  }, {
    path: "/es/charts/apex/data",
    component: _49067db9,
    name: "charts-apex-data___es"
  }, {
    path: "/es/charts/c3/data",
    component: _0a7a35f2,
    name: "charts-c3-data___es"
  }, {
    path: "/es/charts/chartist/data",
    component: _0f662203,
    name: "charts-chartist-data___es"
  }, {
    path: "/es/charts/chartjs/BarChart",
    component: _1357ca78,
    name: "charts-chartjs-BarChart___es"
  }, {
    path: "/es/charts/chartjs/DonutChart",
    component: _01da4455,
    name: "charts-chartjs-DonutChart___es"
  }, {
    path: "/es/charts/chartjs/LineChart",
    component: _67532be1,
    name: "charts-chartjs-LineChart___es"
  }, {
    path: "/es/charts/chartjs/PieChart",
    component: _bd14052a,
    name: "charts-chartjs-PieChart___es"
  }, {
    path: "/es/charts/chartjs/PolarChart",
    component: _0328d88e,
    name: "charts-chartjs-PolarChart___es"
  }, {
    path: "/es/charts/chartjs/RadarChart",
    component: _796fa0f1,
    name: "charts-chartjs-RadarChart___es"
  }, {
    path: "/es/dashboard/analytics/channels",
    component: _17c5e26d,
    name: "dashboard-analytics-channels___es"
  }, {
    path: "/es/dashboard/analytics/overview",
    component: _7c88a0d4,
    name: "dashboard-analytics-overview___es"
  }, {
    path: "/es/dashboard/analytics/social-media",
    component: _6871cfa1,
    name: "dashboard-analytics-social-media___es"
  }, {
    path: "/es/dashboard/analytics/sources",
    component: _bc07acaa,
    name: "dashboard-analytics-sources___es"
  }, {
    path: "/es/dashboard/analytics/users",
    component: _c13ee28a,
    name: "dashboard-analytics-users___es"
  }, {
    path: "/es/ecommerce/customers/data",
    component: _69096963,
    name: "ecommerce-customers-data___es"
  }, {
    path: "/es/ecommerce/orders/data",
    component: _5730585a,
    name: "ecommerce-orders-data___es"
  }, {
    path: "/es/ecommerce/products/data",
    component: _8531515c,
    name: "ecommerce-products-data___es"
  }, {
    path: "/es/tables/advanced/data",
    component: _1af6f029,
    name: "tables-advanced-data___es"
  }, {
    path: "/es/task/kanban/data",
    component: _0485311e,
    name: "task-kanban-data___es"
  }, {
    path: "/fr/apps/calendar/data-calendar",
    component: _ef2d67aa,
    name: "apps-calendar-data-calendar___fr"
  }, {
    path: "/fr/apps/chat/data",
    component: _a9f5c29c,
    name: "apps-chat-data___fr"
  }, {
    path: "/fr/apps/companies/data",
    component: _638eaafd,
    name: "apps-companies-data___fr"
  }, {
    path: "/fr/apps/tickets/data",
    component: _4a38ed09,
    name: "apps-tickets-data___fr"
  }, {
    path: "/fr/charts/apex/data",
    component: _49067db9,
    name: "charts-apex-data___fr"
  }, {
    path: "/fr/charts/c3/data",
    component: _0a7a35f2,
    name: "charts-c3-data___fr"
  }, {
    path: "/fr/charts/chartist/data",
    component: _0f662203,
    name: "charts-chartist-data___fr"
  }, {
    path: "/fr/charts/chartjs/BarChart",
    component: _1357ca78,
    name: "charts-chartjs-BarChart___fr"
  }, {
    path: "/fr/charts/chartjs/DonutChart",
    component: _01da4455,
    name: "charts-chartjs-DonutChart___fr"
  }, {
    path: "/fr/charts/chartjs/LineChart",
    component: _67532be1,
    name: "charts-chartjs-LineChart___fr"
  }, {
    path: "/fr/charts/chartjs/PieChart",
    component: _bd14052a,
    name: "charts-chartjs-PieChart___fr"
  }, {
    path: "/fr/charts/chartjs/PolarChart",
    component: _0328d88e,
    name: "charts-chartjs-PolarChart___fr"
  }, {
    path: "/fr/charts/chartjs/RadarChart",
    component: _796fa0f1,
    name: "charts-chartjs-RadarChart___fr"
  }, {
    path: "/fr/dashboard/analytics/channels",
    component: _17c5e26d,
    name: "dashboard-analytics-channels___fr"
  }, {
    path: "/fr/dashboard/analytics/overview",
    component: _7c88a0d4,
    name: "dashboard-analytics-overview___fr"
  }, {
    path: "/fr/dashboard/analytics/social-media",
    component: _6871cfa1,
    name: "dashboard-analytics-social-media___fr"
  }, {
    path: "/fr/dashboard/analytics/sources",
    component: _bc07acaa,
    name: "dashboard-analytics-sources___fr"
  }, {
    path: "/fr/dashboard/analytics/users",
    component: _c13ee28a,
    name: "dashboard-analytics-users___fr"
  }, {
    path: "/fr/ecommerce/customers/data",
    component: _69096963,
    name: "ecommerce-customers-data___fr"
  }, {
    path: "/fr/ecommerce/orders/data",
    component: _5730585a,
    name: "ecommerce-orders-data___fr"
  }, {
    path: "/fr/ecommerce/products/data",
    component: _8531515c,
    name: "ecommerce-products-data___fr"
  }, {
    path: "/fr/tables/advanced/data",
    component: _1af6f029,
    name: "tables-advanced-data___fr"
  }, {
    path: "/fr/task/kanban/data",
    component: _0485311e,
    name: "task-kanban-data___fr"
  }, {
    path: "/ar/ecommerce/product-detail/:id?",
    component: _4d2211bc,
    name: "ecommerce-product-detail-id___ar"
  }, {
    path: "/ar/email/reademail/:id?",
    component: _695a4ef5,
    name: "email-reademail-id___ar"
  }, {
    path: "/es/ecommerce/product-detail/:id?",
    component: _4d2211bc,
    name: "ecommerce-product-detail-id___es"
  }, {
    path: "/es/email/reademail/:id?",
    component: _695a4ef5,
    name: "email-reademail-id___es"
  }, {
    path: "/fr/ecommerce/product-detail/:id?",
    component: _4d2211bc,
    name: "ecommerce-product-detail-id___fr"
  }, {
    path: "/fr/email/reademail/:id?",
    component: _695a4ef5,
    name: "email-reademail-id___fr"
  }, {
    path: "/ecommerce/product-detail/:id?",
    component: _4d2211bc,
    name: "ecommerce-product-detail-id___en"
  }, {
    path: "/email/reademail/:id?",
    component: _695a4ef5,
    name: "email-reademail-id___en"
  }, {
    path: "/",
    component: _0f1ecc32
  }],

  fallback: false
}

export function createRouter () {
  return new Router(routerOptions)
}
